# Setup
title:            Dubious History
description:      'Alternative History under scrutiny'
url:              https://dubioushistory.github.io
#url:              http://localhost:4000

github:
  repo:           https://github.com/dubioushystory/dubioushistory.github.io

# Rendering
markdown:         kramdown
kramdown:
  hard_wrap: true

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-toc
