# Setup
title:            Dubious History
description:      'Alternative History under closer inspection'
url:              https://dubioushistory.github.io
baseurl:          /

github:
  repo:           https://github.com/dubioushystory/dubioushistory.github.io

# Rendering
markdown:         kramdown
kramdown:
  hard_wrap: true

# Permalinks
permalink:        pretty

# Plugins
plugins:
  - jekyll-toc
